### ISSUE TITLE
Unable to load weights file

### ISSUE THREAD

**Issue by oishi89** [dat-ai/yolov2#2]
Hi there
I got an issue related to load_weights during training my custom data. I was using the weight file downloaded from https://drive.google.com/drive/folders/0ByoFGh573uhzWGx0aXNNNkY5Qms
<img width="1122" alt="screen shot 2017-09-21 at 8 45 54 pm" src="https://user-images.githubusercontent.com/3854757/30728645-51d6be1e-9f0e-11e7-8cd9-76aad3ff86a4.png">

**Comment by datlife** [comment]
May I see how you set up the cfg.py?

**Comment by oishi89** [comment]
Hi please take a look 
`
FEATURE_EXTRACTOR     = 'mobilenet'

CATEGORIES = "/Users/ln160c/Documents/MLWorkspace/yolov2-master/dataset/my_new_dataset/categories.txt
ANCHORS    = "/Users/ln160c/Documents/MLWorkspace/yolov2-master/dataset/my_new_dataset/anchors.txt"


ENABLE_HIERARCHICAL_TREE = False
HIERARCHICAL_TREE_PATH   = "/home/dat/Documents/yolov2/dataset/combined_lisa/lisa.tree"

IMG_INPUT_SIZE = 608

N_CLASSES      = 1

N_ANCHORS      = 5

SHRINK_FACTOR  = 32
`

**Comment by oishi89** [comment]
My bad. I changed the FEATURE_EXTRACTOR = 'mobilenet' but I was using yolo-coco.weight
